name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    # السطرين القادمين هما الحل لفتح الأقفال
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: pypa/buildozer-action@v1
        with:
          buildozer_version: master
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: AlWassel-APK
          path: bin/*.apk
